/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import model.Produto;
import services.ProdutoServices;
import services.ServicesFactory;

/**
 * @author Davi Alves, Kerollyn Lopes
 * @version 0.1 Beta
 * @since 08/04/2019
 */
public class CadProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form PlayerRegistration
     */
    public CadProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlQtd = new javax.swing.JLabel();
        jtNomeProduto = new javax.swing.JTextField();
        jtQtdProduto = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jlTipo = new javax.swing.JLabel();
        jtTipo = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jtValor = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Produto");

        jLayeredPane1.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darcula.selection.color1"));

        jlNome.setText("Nome do Produto");

        jlQtd.setText("Quantidade de Produto(s)");

        jtNomeProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeProdutoKeyPressed(evt);
            }
        });

        jtQtdProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQtdProdutoKeyPressed(evt);
            }
        });

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });
        jbCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCadastrarKeyPressed(evt);
            }
        });

        jlTipo.setText("Tipo do Produto");

        jtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTipoKeyPressed(evt);
            }
        });

        jlValor.setText("Valor do Produto");

        jtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtValorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jlQtd)
                    .addComponent(jlTipo)
                    .addComponent(jlValor))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCadastrar))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtValor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtTipo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtNomeProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo)
                    .addComponent(jtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQtd)
                    .addComponent(jtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlQtd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtNomeProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtQtdProduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlValor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jtValor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void register(){
        try {
            Produto p = new Produto();
            p.setNomeProduto(jtNomeProduto.getText());
            p.setQtdEstoque(Integer.parseInt(jtQtdProduto.getText()));
            p.setTipoProduto(jtTipo.getText());
            p.setValor(Double.parseDouble(jtValor.getText()));
            
            ProdutoServices ps = ServicesFactory.getProdutosServices();
            ps.cadProduto(p);
            
            JOptionPane.showMessageDialog(rootPane, "Produto cadastrado com sucesso!", "Sucesso", JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro! "+e.getMessage(), "erro", JOptionPane.ERROR_MESSAGE);
        }// catch
    }// register
    
    private void clean(){
        jtNomeProduto.setText("");
        jtTipo.setText("");
        jtValor.setText("");
        jtQtdProduto.setText("");
        jtNomeProduto.grabFocus();
    }
    
    private void jtNomeProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTipo.grabFocus();
        }
    }//GEN-LAST:event_jtNomeProdutoKeyPressed

    private void jtQtdProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQtdProdutoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }
    }//GEN-LAST:event_jtQtdProdutoKeyPressed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        register();
        clean();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            register();
            clean();
        }
    }//GEN-LAST:event_jbCadastrarKeyPressed

    private void jtTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTipoKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtValor.grabFocus();
        }
    }//GEN-LAST:event_jtTipoKeyPressed

    private void jtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtValorKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtQtdProduto.grabFocus();
        }
    }//GEN-LAST:event_jtValorKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlQtd;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtNomeProduto;
    private javax.swing.JTextField jtQtdProduto;
    private javax.swing.JTextField jtTipo;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
