package view;

import java.awt.event.KeyEvent;

/** 
 * @author Davi Alves, Kerollyn Lopes
 * @version 0.1 Beta
 * @since 08/04/2019
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdMain = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmRegister = new javax.swing.JMenu();
        jmPlayerRegist = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jmViewPlayers = new javax.swing.JMenu();
        jmClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdMainLayout = new javax.swing.GroupLayout(jdMain);
        jdMain.setLayout(jdMainLayout);
        jdMainLayout.setHorizontalGroup(
            jdMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdMainLayout.setVerticalGroup(
            jdMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jmRegister.setText("Cadastros");

        jmPlayerRegist.setText("Cadastrar Produto");
        jmPlayerRegist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmPlayerRegistMouseClicked(evt);
            }
        });
        jmPlayerRegist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmPlayerRegistKeyPressed(evt);
            }
        });
        jmRegister.add(jmPlayerRegist);

        jMenuBar1.add(jmRegister);

        jMenu1.setText("Ações");

        jmViewPlayers.setText("Ver Estoque");
        jmViewPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmViewPlayersMouseClicked(evt);
            }
        });
        jmViewPlayers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmViewPlayersKeyPressed(evt);
            }
        });
        jMenu1.add(jmViewPlayers);

        jMenuBar1.add(jMenu1);

        jmClose.setText("Fechar");
        jmClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmCloseMouseClicked(evt);
            }
        });
        jmClose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmCloseKeyPressed(evt);
            }
        });
        jMenuBar1.add(jmClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerRegistration() {
        CadProduto pr = new CadProduto();
        jdMain.add(pr);
        pr.setVisible(true);
    }// close method

    private void viewPlayers() {
        Estoque pv = new Estoque();
        jdMain.add(pv);
        pv.setVisible(true);
    }

    private void jmPlayerRegistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmPlayerRegistMouseClicked
        playerRegistration();
    }//GEN-LAST:event_jmPlayerRegistMouseClicked

    private void jmPlayerRegistKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmPlayerRegistKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            playerRegistration();
        }
    }//GEN-LAST:event_jmPlayerRegistKeyPressed

    private void jmCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmCloseMouseClicked

    private void jmCloseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmCloseKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmCloseKeyPressed

    private void jmViewPlayersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmViewPlayersKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            viewPlayers();
        }
    }//GEN-LAST:event_jmViewPlayersKeyPressed

    private void jmViewPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmViewPlayersMouseClicked
        viewPlayers();
    }//GEN-LAST:event_jmViewPlayersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdMain;
    private javax.swing.JMenu jmClose;
    private javax.swing.JMenu jmPlayerRegist;
    private javax.swing.JMenu jmRegister;
    private javax.swing.JMenu jmViewPlayers;
    // End of variables declaration//GEN-END:variables
}
